repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.1
  hooks:
    - id: black
      # It is recommended to specify the latest version of Python
      # supported by your project here, or alternatively use
      # pre-commit's default_language_version, see
      # https://pre-commit.com/#top_level-default_language_version
      #language_version: python3.11
-   repo: https://github.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
    - id: flake8
      exclude: 'tests|env|docs'
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 4.0.1
    hooks:
    - id: pydocstyle
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    - id: mypy

